// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for catalogue documents */
interface CatalogueDocumentData {
    /**
     * title field in *catalogue*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * year field in *catalogue*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    year: prismicT.KeyTextField;
    /**
     * price field in *catalogue*
     *
     * - **Field Type**: Text
     * - **Placeholder**: $999
     * - **API ID Path**: catalogue.price
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    price: prismicT.KeyTextField;
    /**
     * images field in *catalogue*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.images[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    images: prismicT.GroupField<Simplify<CatalogueDocumentDataImagesItem>>;
    /**
     * specs field in *catalogue*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.specs
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    specs: prismicT.RichTextField;
    /**
     * description field in *catalogue*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * more details field in *catalogue*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.more_details
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    more_details: prismicT.RichTextField;
}
/**
 * Item in catalogue → images
 *
 */
export interface CatalogueDocumentDataImagesItem {
    /**
     * image field in *catalogue → images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.images[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * caption field in *catalogue → images*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: catalogue.images[].caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    caption: prismicT.KeyTextField;
}
/**
 * catalogue document from Prismic
 *
 * - **API ID**: `catalogue`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CatalogueDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CatalogueDocumentData>, "catalogue", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<HomepageDocumentDataBodySlice>;
}
/**
 * Item in Homepage → Slice zone → `image_gallery` → Items
 *
 */
export interface HomepageDocumentDataBodyImageGallerySliceItem {
    /**
     * Link to work field in *Homepage → Slice zone → `image_gallery` → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.body[].image_gallery.items[].link_to_work
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_to_work: prismicT.RelationField<"work">;
}
export type HomepageDocumentDataBodyImageGallerySlice = prismicT.Slice<"image_gallery", Record<string, never>, Simplify<HomepageDocumentDataBodyImageGallerySliceItem>>;
/**
 * Slice for *Homepage → Slice zone*
 *
 */
type HomepageDocumentDataBodySlice = HomepageDocumentDataBodyImageGallerySlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * Title field in *Navigation*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Navigation
     * - **API ID Path**: navigation.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Links field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    links: prismicT.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}
/**
 * Item in Navigation → Links
 *
 */
export interface NavigationDocumentDataLinksItem {
    /**
     * Link field in *Navigation → Links*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.links[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.RelationField<"page" | "homepage">;
    /**
     * Link label field in *Navigation → Links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.links[].link_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_label: prismicT.KeyTextField;
}
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<PageDocumentDataBodySlice>;
}
/**
 * Primary content in Page → Slice zone → `text` → Primary
 *
 */
interface PageDocumentDataBodyTextSlicePrimary {
    /**
     * text field in *Page → Slice zone → `text` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Your content here
     * - **API ID Path**: page.body[].text.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
    /**
     * Artist photo field in *Page → Slice zone → `text` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].text.primary.artist_photo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    artist_photo: prismicT.ImageField<never>;
}
export type PageDocumentDataBodyTextSlice = prismicT.Slice<"text", Simplify<PageDocumentDataBodyTextSlicePrimary>, never>;
/**
 * Item in Page → Slice zone → `news_gallery` → Items
 *
 */
export interface PageDocumentDataBodyNewsGallerySliceItem {
    /**
     * Image field in *Page → Slice zone → `news_gallery` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].news_gallery.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Caption field in *Page → Slice zone → `news_gallery` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].news_gallery.items[].caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption: prismicT.RichTextField;
}
export type PageDocumentDataBodyNewsGallerySlice = prismicT.Slice<"news_gallery", Record<string, never>, Simplify<PageDocumentDataBodyNewsGallerySliceItem>>;
/**
 * Primary content in Page → Slice zone → `cv_block` → Primary
 *
 */
interface PageDocumentDataBodyCvBlockSlicePrimary {
    /**
     * Name of block field in *Page → Slice zone → `cv_block` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].cv_block.primary.name_of_block
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name_of_block: prismicT.TitleField;
}
/**
 * Item in Page → Slice zone → `cv_block` → Items
 *
 */
export interface PageDocumentDataBodyCvBlockSliceItem {
    /**
     * Year field in *Page → Slice zone → `cv_block` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].cv_block.items[].year
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    year: prismicT.KeyTextField;
    /**
     * Description field in *Page → Slice zone → `cv_block` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].cv_block.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * On going field in *Page → Slice zone → `cv_block` → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: page.body[].cv_block.items[].on_going
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    on_going: prismicT.BooleanField;
}
export type PageDocumentDataBodyCvBlockSlice = prismicT.Slice<"cv_block", Simplify<PageDocumentDataBodyCvBlockSlicePrimary>, Simplify<PageDocumentDataBodyCvBlockSliceItem>>;
/**
 * Item in Page → Slice zone → `image_gallery` → Items
 *
 */
export interface PageDocumentDataBodyImageGallerySliceItem {
    /**
     * Link to work field in *Page → Slice zone → `image_gallery` → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].image_gallery.items[].link_to_work
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_to_work: prismicT.RelationField<"work">;
}
export type PageDocumentDataBodyImageGallerySlice = prismicT.Slice<"image_gallery", Record<string, never>, Simplify<PageDocumentDataBodyImageGallerySliceItem>>;
/**
 * Slice for *Page → Slice zone*
 *
 */
type PageDocumentDataBodySlice = PageDocumentDataBodyTextSlice | PageDocumentDataBodyNewsGallerySlice | PageDocumentDataBodyCvBlockSlice | PageDocumentDataBodyImageGallerySlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Work documents */
interface WorkDocumentData {
    /**
     * Title field in *Work*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: work.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Text field in *Work*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
    /**
     * Year field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    year: prismicT.KeyTextField;
    /**
     * Frontpage image field in *Work*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: work.frontpage_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    frontpage_image: prismicT.ImageField<never>;
    /**
     * Frontpage video field in *Work*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: If a video is provided, it will override the image.
     * - **API ID Path**: work.frontpage_video
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    frontpage_video: prismicT.LinkToMediaField;
    /**
     * Images field in *Work*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: work.images[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    images: prismicT.GroupField<Simplify<WorkDocumentDataImagesItem>>;
}
/**
 * Item in Work → Images
 *
 */
export interface WorkDocumentDataImagesItem {
    /**
     * Image field in *Work → Images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: work.images[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Caption field in *Work → Images*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.images[].caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    caption: prismicT.KeyTextField;
    /**
     * Video field in *Work → Images*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: work.images[].video
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    video: prismicT.LinkToMediaField;
}
/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;
export type AllDocumentTypes = CatalogueDocument | HomepageDocument | NavigationDocument | PageDocument | WorkDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CatalogueDocumentData, CatalogueDocumentDataImagesItem, CatalogueDocument, HomepageDocumentData, HomepageDocumentDataBodyImageGallerySliceItem, HomepageDocumentDataBodyImageGallerySlice, HomepageDocumentDataBodySlice, HomepageDocument, NavigationDocumentData, NavigationDocumentDataLinksItem, NavigationDocument, PageDocumentData, PageDocumentDataBodyTextSlicePrimary, PageDocumentDataBodyTextSlice, PageDocumentDataBodyNewsGallerySliceItem, PageDocumentDataBodyNewsGallerySlice, PageDocumentDataBodyCvBlockSlicePrimary, PageDocumentDataBodyCvBlockSliceItem, PageDocumentDataBodyCvBlockSlice, PageDocumentDataBodyImageGallerySliceItem, PageDocumentDataBodyImageGallerySlice, PageDocumentDataBodySlice, PageDocument, WorkDocumentData, WorkDocumentDataImagesItem, WorkDocument, AllDocumentTypes };
    }
}
